[package]
name = "keycloak"
version = "0.1.0"
authors = ["caiocesarbosco"]
edition = "2018"

[dependencies]
rust-keycloak = { path = "../rust-keycloak"}
tokio = { version = "1.0", features = ["full"] }